# Site settings
title: Drawing Journey
#email: your-email@domain.com
description: >
    Pleased to meet you! My name is Christoffer and I'm trying to get
    better at drawing. I'm posting my experiences on this blog - what
    worked well, what didn't and what I've learned along the way.
baseurl: ""
url: "http://drawingjourney.com"
twitter_username: drawingjourney
#github_username:  jekyll
permalink: /:title

# Build settings
markdown: kramdown
